---
services:
  web:
    image: sample-flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "300M"
    networks:
      - web-net
networks:
  web-net:
    driver: overlay
...
